# Generated by Django 5.1 on 2025-01-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_shared_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('game_mode', models.CharField(max_length=20)),
                ('round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='pending', max_length=10)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_two', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='my_shared_models.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
